[profile.default]
src = "src"
script = "script"
test = "test"
out = "out"
libs = ["lib"]

solc-version = "0.8.0"

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
