name: test

on:
  push:
    branches:
      - "main"

env:
  FOUNDRY_PROFILE: ci

jobs:
  hello-ethernaut-1:
    strategy:
      fail-fast: true

    name: 1-HelloEthernaut
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Run Forge build
        run: |
          cd 1-hello-ethernaut
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 1-hello-ethernaut
          forge test -vvv
        id: test
  
  fallback-2:
    strategy:
      fail-fast: true

    name: 2-Fallback
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 2-fallback
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 2-fallback
          forge test -vvv
        id: test

  fallout-3:
    strategy:
      fail-fast: true

    name: 3-Fallout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 3-fallout
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 3-fallout
          forge test -vvv
        id: test

  coinflip-4:
    strategy:
      fail-fast: true

    name: 4-CoinFlip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 4-coinflip
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 4-coinflip
          forge test -vvv
        id: test
  
  telephone-5:
    strategy:
      fail-fast: true

    name: 5-Telephone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 5-telephone
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 5-telephone
          forge test -vvv
        id: test
      
  token-6:
    strategy:
      fail-fast: true

    name: 6-Token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 6-token
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 6-token
          forge test -vvv
        id: test

  delegation-7:
    strategy:
      fail-fast: true

    name: 7-Delegation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 7-delegation
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 7-delegation
          forge test -vvv
        id: test