name: test

on:
  push:
    branches:
      - "main"

env:
  FOUNDRY_PROFILE: ci

jobs:
  hello-ethernaut-0:
    strategy:
      fail-fast: true

    name: 0-HelloEthernaut
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Run Forge build
        run: |
          cd 0-hello-ethernaut
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 0-hello-ethernaut
          forge test -vvv
        id: test
  
  fallback-1:
    strategy:
      fail-fast: true

    name: 1-Fallback
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 1-fallback
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 1-fallback
          forge test -vvv
        id: test

  fallout-2:
    strategy:
      fail-fast: true

    name: 2-Fallout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 2-fallout
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 2-fallout
          forge test -vvv
        id: test

  coinflip-3:
    strategy:
      fail-fast: true

    name: 3-CoinFlip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 3-coinflip
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 3-coinflip
          forge test -vvv
        id: test
  
  telephone-4:
    strategy:
      fail-fast: true

    name: 4-Telephone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 4-telephone
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 4-telephone
          forge test -vvv
        id: test
      
  token-5:
    strategy:
      fail-fast: true

    name: 5-Token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 5-token
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 5-token
          forge test -vvv
        id: test

  delegation-6:
    strategy:
      fail-fast: true

    name: 6-Delegation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd 6-delegation
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd 6-delegation
          forge test -vvv
        id: test