[profile.default]
src = "src"
script = "script"
test = "test"
out = "out"
libs = ["lib"]
block_gas_limit = 30000000

solc-version = "0.6.12"

remappings = ["openzeppelin-contracts-06=lib/openzeppelin-contracts/contracts"]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
